# Generated by Django 4.1 on 2022-09-02 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_hotel_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('pickup_location', models.CharField(choices=[('airport suisse side', 'airport suisse side'), ('airport french side', 'airport french side'), ('private flight', 'private flight'), ('Novotel Genève Aéroport France', 'Novotel Genève Aéroport France'), ('M3 Hôtel & Résidence Ferney Geneva Airport', 'M3 Hôtel & Résidence Ferney Geneva Airport')], max_length=100)),
                ('drop_location', models.CharField(choices=[('airport suisse side', 'airport suisse side'), ('airport french side', 'airport french side'), ('private flight', 'private flight'), ('Novotel Genève Aéroport France', 'Novotel Genève Aéroport France'), ('M3 Hôtel & Résidence Ferney Geneva Airport', 'M3 Hôtel & Résidence Ferney Geneva Airport')], max_length=100)),
                ('total_seats', models.IntegerField()),
                ('seats_available', models.IntegerField(blank=True, null=True)),
                ('seats_booked', models.IntegerField(blank=True, default=0, null=True)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
            ],
        ),
        migrations.CreateModel(
            name='ShuttleReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.IntegerField()),
                ('shuttle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuttle.shuttle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
