# Generated by Django 4.1 on 2022-09-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
