# Generated by Django 4.0.5 on 2022-09-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='ad_type',
            field=models.CharField(choices=[('rent', 'rent'), ('sell', 'sell'), ('student_house', 'student_house')], default='rent', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location_long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('villa', 'villa'), ('apartment', 'apartment'), ('house', 'house'), ('office', 'office'), ('shop', 'shop')], default='apartment', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='space',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
